import LocalizedStrings from 'react-native-localization';
export const localStrings = new LocalizedStrings({
  'en-US': {
    number: '60k+',
    premiumRecipe: ' Premium recipies',
    yummTitle: 'Yumm',
    findRecipe: 'Find the best recipes for cooking',
    signUp: 'Sign up',
    startCooking: 'Start cooking',
    sampleQty: '200 mg',
    ingredientsTitle: 'Ingredients',
    itemsTitle: 'Items',
    defaultRating: '4.5',
    defaultReviews: '300 Reviews',
    authorTitle: 'By Niki Samantha',
    locationTitle: 'Bali, Indonesia',
    followTitle: 'Follow',
    trendingTitle: 'Trending Now',
    recentDefaultTitle: 'Indonesian chicken burger',
    recentDefaultDescription: 'By James Wolden',
    popularDefaultTitle: 'Indonesian chicken burger',
    recentTitle: 'Recent Recipe',
    popularTitle: 'Popular Creator',
    seeAll: 'See all',
    firstNameTitle: 'First Name',
    lastNameTitle: 'Last Name',
    emailTitle: 'Email',
    passwordTitle: 'Password',
    guestTitle: 'Guest',
    goodTitle: 'Good ',
    morningTitle: 'morning',
    afternoonTitle: 'afternoon',
    eveningTitle: 'evening',
    searchRecipes: 'Search recipes',
    invalidDataTitle: 'Invalid Data',
    invalidDataMessage: 'Please enter valid data',
  },
  it: {
    number: '60k+',
    premiumRecipe: ' Premium recipies',
    yummTitle: 'Yumm',
    findRecipe: 'Find the best recipes for cooking',
    signUp: 'Sign up',
    startCooking: 'Start cooking',
    sampleQty: '200 mg',
    ingredientsTitle: 'Ingredients',
    itemsTitle: 'Items',
    defaultRating: '4.5',
    defaultReviews: '300 Reviews',
    authorTitle: 'By Niki Samantha',
    locationTitle: 'Bali, Indonesia',
    followTitle: 'Follow',
    trendingTitle: 'Trending Now',
    recentDefaultTitle: 'Indonesian chicken burger',
    recentDefaultDescription: 'By James Wolden',
    popularDefaultTitle: 'Indonesian chicken burger',
    recentTitle: 'Recent Recipe',
    popularTitle: 'Popular Creator',
    seeAll: 'See all',
    firstNameTitle: 'First Name',
    lastNameTitle: 'Last Name',
    emailTitle: 'Email',
    passwordTitle: 'Password',
    guestTitle: 'Guest',
    goodTitle: 'Good ',
    morningTitle: 'morning',
    afternoonTitle: 'afternoon',
    eveningTitle: 'evening',
    searchRecipes: 'Search recipes',
    invalidDataTitle: 'Invalid Data',
    invalidDataMessage: 'Please enter valid data',
  },
});
localStrings.setLanguage('en');
